<<<<<<< HEAD
version: '3'                                        # Versión del formato de docker-compose

services:
  influxdb:
    image: influxdb:1.8                             # Usa la imagen oficial de influxdb 1.8
    container_name: influxdb                        # Nombre del contenedor# Nombre del contenedor
    ports:
      - "8086:8086"                                 # Publica el puerto 8086 para la api http
    volumes:
      - influxdb-data:/var/lib/influxdb             # Persistencia de datos en un volumen docker

  telegraf:
    image: telegraf:latest                          # Imagen de telegraf para recopilar métricas
    container_name: telegraf
    depends_on:
      - influxdb                                    # Espera a influxdb antes de arrancar
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Monta la configuración de telegraf en modo solo lectura

  grafana:
    image: grafana/grafana:latest                   # Imagen oficial de grafana para dashboards
    container_name: grafana                         
    ports:
      - "3000:3000"                                 # Publica el puerto 3000 para la interfaz web
    volumes:
      - grafana-data:/var/lib/grafana               # Persiste datos y configuraciones de grafana

volumes:
  influxdb-data:                                    # Volumen dedicado para los datos de influxdb
  grafana-data:                                     # Volumen dedicado para los datos y dashboards de grafana
=======
<<<<<<< HEAD
version: '3'  # Versión del formato de docker-compose

services:
  influxdb:
    image: influxdb:latest                          # Usa la imagen oficial más reciente de InfluxDB (2.x)
    container_name: influxdb                        # Nombre del contenedor
    ports:
      - "8086:8086"                                 # Publica el puerto 8086 en el host
    volumes:
      - influxdb-data:/var/lib/influxdb2            # Persistencia de datos en la ruta de InfluxDB 2.x
    env_file:
      - .env                                         # carga todas las DOCKER_INFLUXDB_* y las demás
    environment:
      - DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
  telegraf:
    image: telegraf:latest                         # Imagen de Telegraf para recopilar métricas MQTT
    container_name: telegraf                       # Nombre del contenedor
    depends_on:
      - influxdb                                   # Espera a que InfluxDB esté listo antes de arrancar
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  
                                                   # Monta la configuración de Telegraf en modo solo lectura
    env_file:
      - .env
    environment:
      - INFLUX_TOKEN
      - INFLUX_ORG
      - INFLUX_BUCKET
  grafana:
    image: grafana/grafana:latest                  # Imagen oficial de Grafana para dashboards
    container_name: grafana                        # Nombre del contenedor
    ports:
      - "3000:3000"                                # Publica el puerto 3000 en el host
    volumes:
      - grafana-data:/var/lib/grafana              # Persiste datos y configuraciones de Grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}

volumes:
  influxdb-data:  # Volumen dedicado para los datos de InfluxDB
  grafana-data:   # Volumen dedicado para los datos y dashboards de Grafana
=======
version: '3'                                        # Versión del formato de docker-compose

services:
  influxdb:
    image: influxdb:1.8                             # Usa la imagen oficial de influxdb 1.8
    container_name: influxdb                        # Nombre del contenedor# Nombre del contenedor
    ports:
      - "8086:8086"                                 # Publica el puerto 8086 para la api http
    volumes:
      - influxdb-data:/var/lib/influxdb             # Persistencia de datos en un volumen docker

  telegraf:
    image: telegraf:latest                          # Imagen de telegraf para recopilar métricas
    container_name: telegraf
    depends_on:
      - influxdb                                    # Espera a influxdb antes de arrancar
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Monta la configuración de telegraf en modo solo lectura

  grafana:
    image: grafana/grafana:latest                   # Imagen oficial de grafana para dashboards
    container_name: grafana                         
    ports:
      - "3000:3000"                                 # Publica el puerto 3000 para la interfaz web
    volumes:
      - grafana-data:/var/lib/grafana               # Persiste datos y configuraciones de grafana

volumes:
  influxdb-data:                                    # Volumen dedicado para los datos de influxdb
  grafana-data:                                     # Volumen dedicado para los datos y dashboards de grafana
>>>>>>> 574321047df6fc4b22468f4dd7fc3a49a772ef77
>>>>>>> c9e17441fbe05838da6a2e3ba14cdb532dadcb14
